### ISSUE TITLE
GarbageCollector not imported

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-generator#18]
As @rainman110 noticed, the GarbageCollector module is not imported anymore. Thus, object destructor method are never properly called. See https://github.com/tpaviot/pythonocc-core/issues/199

**Comment by tpaviot** [comment]
It seems this missing import comes from the move from gccxml to cppheaderparser.

I dived into the old pythonocc-2.5 code, it appears that each .i SWIG file imports the GarbageCollector module at the beginning of the file.

**Comment by rainman110** [comment]
@tpaviot This issue is already closed since 0712998fd041944
