### ISSUE TITLE
Make arrays (such as  TColgp_Array1OfPnt) support the iterator interface

### ISSUE THREAD

**Issue by alynch4047** [tpaviot/pythonocc-generator#29]
It would be nice to be able to iterate over wrapped arrays using normal python idioms. I believe we could achieve this by `%extend%`ing the array classes with 3 extra functions
 `__iter__`, 
 `__next__`,
  `next`

(See: http://stackoverflow.com/questions/13094421/what-is-the-interface-for-python-iterators)

This falls into the nice-to-have category, but I think is fairly simple to add to the wrapper generator. I might have a go at this next weekend if I get the time.

**Comment by jf---** [comment]
Wow, that's a very interesting idea @alynch4047 ....

**Comment by tpaviot** [comment]
fixed by pr #48
