### ISSUE TITLE
OCE 0.17 methods that end on "_ShallowCopy" have undefined symbols

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-generator#3]
modules affected: _Visual3d.so, _Graphic3d.so, IFSelect.so, _TShort.so, _TColGeom.so, _TColGeom2d.so, _TColgp.so, _ProjLib.so, _ChFiDS.so, _Interface.so, _GeomPlate.so, _Units.so, _Geom.so, _TColStd.so, _Contap.so, _GeomFill.so, _Storage.so, _Interface.so

**Comment by tpaviot** [comment]
Please paste here the complete compiler trace, it's necessary to decide what to do (fix the wrapper, or remove the related method from the list of wrapped method).

**Comment by jf---** [comment]
see #1
