### ISSUE TITLE
OCE 0.17 forward declaration of 'BRepAdaptor_Surface'

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-generator#5]
affected modules: _BRepClass3d.so, BRepApprox.so
possible: _ChFi3d

**Comment by tpaviot** [comment]
Please paste the complete compiler trace.

**Comment by jf---** [comment]
see #1

**Comment by jf---** [comment]
same thing, in another module:



[  9%] Building CXX object CMakeFiles/_BRepApprox.dir/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx.o
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:31:108: error: member access into incomplete type
      'const BRepAdaptor_Surface'
inline Standard_Real BRepApprox_SurfaceTool::FirstUParameter(const BRepAdaptor_Surface& Surf){  return Surf.FirstUParameter(); }
                                                                                                           ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:32:108: error: member access into incomplete type
      'const BRepAdaptor_Surface'
inline Standard_Real BRepApprox_SurfaceTool::FirstVParameter(const BRepAdaptor_Surface& Surf){  return Surf.FirstVParameter();}
                                                                                                           ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:33:107: error: member access into incomplete type
      'const BRepAdaptor_Surface'
inline Standard_Real BRepApprox_SurfaceTool::LastUParameter(const BRepAdaptor_Surface& Surf){  return Surf.LastUParameter();}
                                                                                                          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:34:107: error: member access into incomplete type
      'const BRepAdaptor_Surface'
inline Standard_Real BRepApprox_SurfaceTool::LastVParameter(const BRepAdaptor_Surface& Surf){  return Surf.LastVParameter();}
                                                                                                          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:38:14: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return Surf.NbUIntervals(S);
             ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:43:14: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return Surf.NbVIntervals(S);
             ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:49:7: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  Surf.UIntervals(Tab,S);
      ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:55:7: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  Surf.VIntervals(Tab,S);
      ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:63:14: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return Surf.UTrim(F,L,Tol);
             ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:70:14: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return Surf.VTrim(F,L,Tol);
             ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:78:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.IsUClosed();
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:83:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.IsVClosed();
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:88:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.IsUPeriodic();
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:93:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.UPeriod();
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:98:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.IsVPeriodic();
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:103:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.VPeriod();
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:110:11: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  return S.Value(U,V);
          ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:118:4: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  S.D0(U,V,P);
   ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
In file included from /Users/jelleferinga/GIT/pythonocc-core-occ-690/build/Darwin/x86_64-MinSizeRel-64/BRepApproxPYTHON_wrap.cxx:3915:
In file included from /Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.hxx:149:
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_SurfaceTool.lxx:128:4: error: member access into incomplete type
      'const BRepAdaptor_Surface'
  S.D1(U,V,P,D1U,D1V);
   ^
/Users/jelleferinga/miniconda/envs/oce_0.17/include/oce/BRepApprox_Approx.hxx:23:7: note: forward declaration of 'BRepAdaptor_Surface'
class BRepAdaptor_Surface;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
