### ISSUE TITLE
Bug: Wrong position of %wrap_handle

### ISSUE THREAD

**Issue by rainman110** [tpaviot/pythonocc-generator#55]
In e.g. StepShape.i, some %wrap_handle(xxx) come too late. All %wrap_handle calls must be in front of the first class declaration.

**Comment by tpaviot** [comment]
Interface files were updated on the pythonocc-core side (see https://github.com/tpaviot/pythonocc-core/commit/1d7982b06a1a6fc0aa05baa39a490eb317498bb3). However, there's not any difference at compilation time, what about runtime ?

**Comment by rainman110** [comment]
I am working on it. It requires many new imports. Takes a while to go through it manually.

**Comment by rainman110** [comment]
@tpaviot What I am currently working on is the following:

I renamed all opencascade::handle<xxx> occurences to OccHandle_XXX. This OccHandl_XXX is defined in %wrap_handle.

Therefore, to successfully compile the module, the wrap_handle of a class must be imported. This way, you can make sure to not forget any import related to handles.

**Comment by rainman110** [comment]
IMHO, failing early (at compile time) is much better than failing at runtime (at some user).

It requires too many tests to check all of these problems at runtime.

**Comment by rainman110** [comment]
This is not yet fixed in the generator! There are still wrap_handles for the H-Classes, e.g. %wrap_handle(StepShape_HArray1OfShapeDimensionRepresentationItem) at the bottom of StepShape.i

**Comment by rainman110** [comment]
I fixed it locally. Shall I make a PR?

**Comment by tpaviot** [comment]
No need for a PR, I cherry-picked it. Thank you.
