### ISSUE TITLE
OCCT 7.4.0: No handle detected for class BRepMesh_VertexTool

### ISSUE THREAD

**Issue by rainman110** [tpaviot/pythonocc-generator#59]
It is derived from Standard_Transient and therefore must be wrapped in a handle.

**Comment by tpaviot** [comment]
Yes, I realize that classes the inherit from Standard_Transient are not detected anymore by the generator. There are hundreds of such cases, no need to open an issue for each one

**Comment by rainman110** [comment]
Fixed
