### ISSUE TITLE
Missing TopoDS_Shape constructor

### ISSUE THREAD

**Issue by rainman110** [tpaviot/pythonocc-generator#62]
At the moment, there is no way to create an empty TopoDS_Shape. This is however required in some cases.

Therefore, the disabled constructor has to be enabled again (see Modules.py=

**Comment by tpaviot** [comment]
Right, it was removed (I don't remember why), but is widely used in the examples section. It has to come back.

**Comment by rainman110** [comment]
I know already, why you removed it. It pulls in two constructors. One with a template argument, which is not put correctly into the swig input file. Hence, you'll get compilation errors.

It would be nice to be able to exactly specify, which methods to prune when there are multiple versios of one method.

**Comment by tpaviot** [comment]
Currently all methods names that are excluded, there's no way to choose if we can keep some of them.

Ugly hack at 9034dc5. But that works (tested)
