### ISSUE TITLE
Remove operating system header information in wrapper files

### ISSUE THREAD

**Issue by rainman110** [tpaviot/pythonocc-generator#69]
The problem is, that depending on the computer, all wrapper files will be marked as changed and will have changed this line, even if everything else is the same.

This makes it IMHO impractical for version control.

A alternative would be a separate text file that contains the metadata,

**Comment by tpaviot** [comment]
For the same reason, I already removed the timestamp.

A separate text is a good option, it could include as well the console output from the generator.
