### ISSUE TITLE
OCE 0.17 undefined symbol: Geom2dGcc_FunctionTanCuCuCu

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-generator#7]
Scanning dependencies of target _Geom2dGcc
Building CXX object CMakeFiles/_Geom2dGcc.dir/Darwin/x86_64-MinSizeRel-64/Geom2dGccPYTHON_wrap.cxx.o
Linking CXX shared module Darwin/x86_64-MinSizeRel-64/_Geom2dGcc.so
Undefined symbols for architecture x86_64:
  "Geom2dGcc_FunctionTanCuCuCu::Geom2dGcc_FunctionTanCuCuCu(Geom2dAdaptor_Curve const&, gp_Pnt2d const&, gp_Pnt2d const&)", referenced from:
      _wrap_new_Geom2dGcc_FunctionTanCuCuCu__SWIG_8(_object*, int, _object**) in Geom2dGccPYTHON_wrap.cxx.o
  "Geom2dGcc_FunctionTanCuCuCu::Geom2dGcc_FunctionTanCuCuCu(gp_Lin2d const&, Geom2dAdaptor_Curve const&, gp_Pnt2d const&)", referenced from:
      _wrap_new_Geom2dGcc_FunctionTanCuCuCu__SWIG_7(_object*, int, _object**) in Geom2dGccPYTHON_wrap.cxx.o
  "Geom2dGcc_FunctionTanCuCuCu::Geom2dGcc_FunctionTanCuCuCu(gp_Circ2d const&, Geom2dAdaptor_Curve const&, gp_Pnt2d const&)", referenced from:
      _wrap_new_Geom2dGcc_FunctionTanCuCuCu__SWIG_6(_object*, int, _object**) in Geom2dGccPYTHON_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Darwin/x86_64-MinSizeRel-64/_Geom2dGcc.so] Error 1
make[2]: *** [CMakeFiles/_Geom2dGcc.dir/all] Error 2
make[1]: *** [CMakeFiles/_Geom2dGcc.dir/rule] Error 2
make: *** [_Geom2dGcc] Error 2
[100%] Swig source

**Comment by tpaviot** [comment]
Remove this class from the wrapper. To remove the class, add its name to the list of excluded class from the Geom2dGcc module. In Modules.py:
<pre>
('Geom2dGcc', [], ['Geom2dGcc_FuncTCuCuCuOfMyC2d3Tan', 'Geom2dGcc_FunctionTanCuCuCu'],
            {'Geom2dGcc_Lin2dTanObl': 'IsParallel2'}),
</pre>
And relaunch the wrapper generation for the Geom2dGcc module only.
