### ISSUE TITLE
Reuse potential

### ISSUE THREAD

**Issue by Vanuan** [tpaviot/pythonocc-generator#80]
I'm wondering how complex would it be to reuse the generator approach for other C++ libraries?

For example pivy.coin3d: https://github.com/coin3d/pivy/issues/71

If you started from scratch, would you go with it again? Or would you rather push for more advanced SWIG support?

How time consuming is it compared to manual coding?

**Comment by cafhach** [comment]
My impression is that the code is pretty OpenCASCADE-specific so I don't think there's a lot of potential
